// This file was autogenerated by closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../demojs/example-component.js', ['example.Dialog'], ['goog.ui.Component']);
goog.addDependency('../../../demojs/example-page.js', ['page.Demo'], ['example.Dialog']);
